<?php

declare(strict_types=1);

namespace App\Services;

/**
 * The recurring tournament rota: a pure function of time (no DB access, no
 * side effects). Given a UTC window, returns every occurrence that *should*
 * exist in it. scripts/schedule_tournaments.php is the only caller that turns
 * these into rows — it inserts whatever isn't there yet, keyed by
 * `schedule_key`, and never touches an existing row.
 *
 * All times are UTC. Every occurrence starts exactly on the hour, so the
 * whole rota can be generated by walking hour boundaries and asking each one
 * "what fires here" (see occurrencesAtHour()). That keeps this trivially easy
 * to extend: add a case to one of the per-rota match arms below.
 *
 * The rota (see class-level docs in the task/PR for the source spec):
 *
 *   hourly          every hour, rotating pool by hour%4 (bullet/blitz/blitz/rapid)
 *   variant-hourly  every 3rd hour, rotating variant by (hour/3)%4
 *   daily           4 fixed daily slots (05:00, 17:00, 18:00, 19:00)
 *   weekly          one arena most days at 17:00 (Thu 19:00), Tue has two
 *   titled-tuesday  Tue 18:00, titled-players-only — its own series
 *   monthly         last Sunday of the month, 16:00
 *
 * ~37 tournaments/day; overlap between rotas is expected and fine.
 */
final class TournamentSchedule
{
    /**
     * @return list<array{
     *   schedule_key:string, series:string, name:string, variant:string,
     *   pool:string, starts_at:string, duration_minutes:int, rated:bool,
     *   min_rating:?int, max_rating:?int, titled_only:bool
     * }>
     */
    public static function occurrencesBetween(int $fromTs, int $toTs): array
    {
        if ($toTs <= $fromTs) {
            return [];
        }

        $occurrences = [];
        $hourTs = $fromTs - ($fromTs % 3600);
        for ($ts = $hourTs; $ts < $toTs; $ts += 3600) {
            if ($ts < $fromTs) {
                continue;
            }

            foreach (self::occurrencesAtHour($ts) as $occ) {
                $occurrences[] = $occ;
            }
        }

        return $occurrences;
    }

    /**
     * The longest `duration_minutes` anywhere in the rota (currently the
     * monthly championship at 240). Computed by actually walking
     * {@see self::occurrencesAtHour()} over a window long enough to be sure
     * every rota entry fires at least once — including the once-a-month
     * one — rather than hardcoding a number that would silently go stale the
     * next time someone adds a longer-running event.
     *
     * Callers use this to size how far back they need to look for
     * occurrences that started in the past but haven't ended yet (a cold
     * start / gap in the scheduler timer). Pure function of the rota, no I/O.
     */
    public static function maxDurationMinutes(): int
    {
        // 40 days comfortably covers every recurrence period in the rota
        // (hourly/daily/weekly all repeat well within a week; "last Sunday of
        // the month" repeats at most every ~31 days), regardless of which
        // date we start scanning from.
        $anchor = gmmktime(0, 0, 0, 1, 1, 2024);
        $windowHours = 40 * 24;

        $max = 0;
        for ($i = 0; $i < $windowHours; $i++) {
            foreach (self::occurrencesAtHour($anchor + $i * 3600) as $occ) {
                if ($occ['duration_minutes'] > $max) {
                    $max = $occ['duration_minutes'];
                }
            }
        }

        return $max;
    }

    /**
     * @return list<array{
     *   schedule_key:string, series:string, name:string, variant:string,
     *   pool:string, starts_at:string, duration_minutes:int, rated:bool,
     *   min_rating:?int, max_rating:?int, titled_only:bool
     * }>
     */
    private static function occurrencesAtHour(int $ts): array
    {
        $hour = (int) gmdate('G', $ts);

        // Reduced to a single arena a day — the 18:00 UTC Daily Blitz — to stop
        // the bot backfill from manufacturing tens of thousands of filler
        // games. The full rota (hourly/variant-hourly/weekly/monthly, plus the
        // other daily slots) is intentionally left defined below but uncalled,
        // so restoring it is a one-line change here.
        if ($hour === 18) {
            $daily = self::daily($ts, $hour);
            if ($daily !== null) {
                return [$daily];
            }
        }

        return [];
    }

    /**
     * "Hourly" in a name is a promise: this event fits inside the hour it
     * started in, so by the time the next hourly-slot event appears the
     * previous one is gone. Bullet (27min) and Blitz (57min) keep that
     * promise. A real 10+0 rapid game needs more than an hour to be worth
     * playing, so its 117-minute slot can't keep it — we don't rename the
     * duration down to a rushed non-rapid pairing window just to keep the
     * word "Hourly"; we drop the word instead. It's still on the hourly
     * rotation (hour%4===3), it just isn't advertised as finishing hourly.
     *
     * @return array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool}
     */
    private static function hourly(int $ts, int $hour): array
    {
        [$name, $pool, $duration, $slug] = match ($hour % 4) {
            0 => ['Hourly Bullet Arena', '1+0', 27, 'bullet'],
            1 => ['Hourly Blitz Arena', '3+0', 57, 'blitz'],
            2 => ['Hourly Blitz Arena', '5+0', 57, 'blitz'],
            3 => ['Rapid Arena', '10+0', 117, 'rapid'],
        };

        return self::build('hourly', $slug, $ts, $name, 'standard', $pool, $duration);
    }

    /** @return array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool} */
    private static function variantHourly(int $ts, int $hour): array
    {
        $idx = intdiv($hour, 3) % 4;
        [$variant, $pool, $slug, $label] = match ($idx) {
            0 => ['chess960', '3+0', 'chess960', 'Chess960'],
            1 => ['crazyhouse', '3+0', 'crazyhouse', 'Crazyhouse'],
            2 => ['duck', '5+0', 'duck', 'Duck'],
            3 => ['antichess', '3+0', 'antichess', 'Antichess'],
        };

        return self::build('variant-hourly', $slug, $ts, "Hourly {$label} Arena", $variant, $pool, 57);
    }

    /** @return ?array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool} */
    private static function daily(int $ts, int $hour): ?array
    {
        return match ($hour) {
            5 => self::build('daily', 'eastern-blitz', $ts, 'Eastern Blitz Arena', 'standard', '3+0', 120),
            17 => self::build('daily', 'bullet', $ts, 'Daily Bullet Arena', 'standard', '1+0', 60),
            18 => self::build('daily', 'blitz', $ts, 'Daily Blitz Arena', 'standard', '5+0', 120),
            19 => self::build('daily', 'rapid', $ts, 'Daily Rapid Arena', 'standard', '10+0', 150),
            default => null,
        };
    }

    /** @return ?array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool} */
    private static function weekly(int $ts, int $dow, int $hour): ?array
    {
        return match (true) {
            $dow === 1 && $hour === 17 => self::build('weekly', 'bullet', $ts, 'Weekly Bullet Arena', 'standard', '1+0', 180),
            $dow === 2 && $hour === 17 => self::build('weekly', 'titled-tuesday-warmup', $ts, 'Titled Tuesday Warm-up', 'standard', '3+0', 60),
            $dow === 2 && $hour === 18 => self::build('titled-tuesday', 'titled-tuesday', $ts, 'Titled Tuesday', 'standard', '5+0', 120, null, null, true),
            $dow === 3 && $hour === 17 => self::build('weekly', 'rapid', $ts, 'Weekly Rapid Arena', 'standard', '10+0', 240),
            $dow === 4 && $hour === 19 => self::build('weekly', 'thunder', $ts, 'Thursday Thunder', 'standard', '1+0', 90),
            $dow === 5 && $hour === 17 => self::build('weekly', 'chess960', $ts, 'Weekly Chess960 Arena', 'chess960', '3+0', 180),
            $dow === 6 && $hour === 17 => self::build('weekly', 'elite-weekend', $ts, 'Elite Weekend Arena', 'standard', '3+0', 120, 2000),
            $dow === 7 && $hour === 17 => self::build('weekly', 'blitz', $ts, 'Weekly Blitz Arena', 'standard', '5+0', 180),
            default => null,
        };
    }

    /** @return ?array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool} */
    private static function monthly(int $ts, int $dow, int $hour, int $day, int $daysInMonth): ?array
    {
        // Last Sunday of the month: a Sunday with no other Sunday after it
        // this month, i.e. adding 7 days would overflow into next month.
        if ($dow === 7 && $hour === 16 && ($day + 7) > $daysInMonth) {
            return self::build('monthly', 'championship', $ts, 'Monthly Championship', 'standard', '5+0', 240);
        }

        return null;
    }

    /** @return array{schedule_key:string, series:string, name:string, variant:string, pool:string, starts_at:string, duration_minutes:int, rated:bool, min_rating:?int, max_rating:?int, titled_only:bool} */
    private static function build(
        string $series,
        string $slug,
        int $ts,
        string $name,
        string $variant,
        string $pool,
        int $durationMinutes,
        ?int $minRating = null,
        ?int $maxRating = null,
        bool $titledOnly = false,
    ): array {
        return [
            'schedule_key' => sprintf('%s-%s-%s', $series, $slug, gmdate('Y-m-d\TH:i:s\Z', $ts)),
            'series' => $series,
            'name' => $name,
            'variant' => $variant,
            'pool' => $pool,
            'starts_at' => gmdate('Y-m-d H:i:s', $ts),
            'duration_minutes' => $durationMinutes,
            'rated' => true,
            'min_rating' => $minRating,
            'max_rating' => $maxRating,
            'titled_only' => $titledOnly,
        ];
    }
}
