// Package openings is the engine's source of truth for opening NAMES (ECO
// classification). It holds a static table — generated by `gomachine
// compile-openings` from the Lichess chess-openings dataset (CC0) — mapping a
// position's native Zobrist key to its {ECO, Name}.
//
// Keying by our own pos.Key() (not a move sequence, not Polyglot's hash) makes
// classification transposition-correct for free: any move order reaching the same
// position resolves to the same name. The matching rule is Lichess's "deepest
// named position along the line wins" (Classify), so a position past the last
// named node still reports the opening it belongs to.
//
// This is read-only, in-binary knowledge: no file I/O, no startup cost. Any
// caller that has a position (engine, hub, /analyze) can name it.
package openings

import "sort"

// Opening is an ECO code + full name, e.g. {"B90", "Sicilian Defense: Najdorf
// Variation"}.
type Opening struct {
	ECO  string `json:"eco"`
	Name string `json:"name"`
}

// entry is one row of the generated table (sorted ascending by Key).
type entry struct {
	Key uint64
	ECO string
	Nam string
}

// Lookup returns the opening named by an EXACT position key, or ok=false. O(log n)
// binary search over the key-sorted generated table.
func Lookup(key uint64) (Opening, bool) {
	i := sort.Search(len(table), func(i int) bool { return table[i].Key >= key })
	if i < len(table) && table[i].Key == key {
		return Opening{ECO: table[i].ECO, Name: table[i].Nam}, true
	}
	return Opening{}, false
}

// Classify names a line given its position keys in order (root→leaf, inclusive).
// It returns the DEEPEST (last) position that matches a named entry — the Lichess
// rule — so a longer, more specific variation supersedes its parent family, and a
// position beyond book still carries the opening it came from. ok=false if no
// position along the line is named.
func Classify(keys []uint64) (Opening, bool) {
	var found Opening
	ok := false
	for _, k := range keys {
		if o, hit := Lookup(k); hit {
			found, ok = o, true
		}
	}
	return found, ok
}

// Len reports how many named positions the table holds (diagnostics).
func Len() int { return len(table) }
