package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/timanthonyalexander/gomachine/internal/chess"
)

// cmdCompileOpenings generates internal/openings/table_gen.go: a static table
// mapping each named opening's final position (keyed by OUR native Zobrist,
// pos.Key()) to its ECO code + name. It reads the committed Lichess opening TSVs
// (data/openings/a.tsv..e.tsv: eco, name, pgn-in-SAN) and replays each line
// through internal/chess, so the key uses our movegen + castling/EP normalization
// — runtime lookups (engine.Classify) therefore match byte-for-byte.
//
// This is the ECO-naming analogue of compile-book, but it stores names (not
// evals) and emits Go source (not a binary sidecar): the table is small, static,
// and must exactly match our key, so build-time generation beats a runtime file.
func cmdCompileOpenings(args []string) {
	fs := flag.NewFlagSet("compile-openings", flag.ExitOnError)
	openings := fs.String("openings", "data/openings", "dir of Lichess opening TSVs (a.tsv..e.tsv)")
	out := fs.String("out", "internal/openings/table_gen.go", "output generated Go file")
	_ = fs.Parse(args)

	rows, err := readOpeningRows(*openings)
	if err != nil {
		fmt.Fprintln(os.Stderr, "compile-openings:", err)
		os.Exit(1)
	}

	// Replay each named line to its final position; key it by our Zobrist. On the
	// rare collision (two lines ending on the same position) the last writer wins.
	type named struct {
		key      uint64
		eco, nam string
	}
	byKey := map[uint64]named{}
	skipped := 0
	for _, r := range rows {
		pos, perr := chess.ParseFEN(chess.StartFEN)
		if perr != nil {
			continue
		}
		ok := true
		for _, san := range r.sans {
			m, found := matchSAN(pos, san)
			if !found {
				ok = false
				break
			}
			var u chess.Undo
			pos.DoMove(m, &u)
		}
		if !ok || len(r.sans) == 0 {
			skipped++
			continue
		}
		byKey[pos.Key()] = named{pos.Key(), r.eco, r.nam}
	}

	sorted := make([]named, 0, len(byKey))
	for _, n := range byKey {
		sorted = append(sorted, n)
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].key < sorted[j].key })

	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "compile-openings:", err)
		os.Exit(1)
	}
	f, err := os.Create(*out)
	if err != nil {
		fmt.Fprintln(os.Stderr, "compile-openings:", err)
		os.Exit(1)
	}
	defer f.Close()
	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "// Code generated by \"gomachine compile-openings\"; DO NOT EDIT.")
	fmt.Fprintln(w, "// Source: lichess-org/chess-openings (CC0), re-keyed onto our native Zobrist.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package openings")
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "// table holds %d named positions, sorted ascending by Key for binary search.\n", len(sorted))
	fmt.Fprintln(w, "var table = []entry{")
	for _, n := range sorted {
		fmt.Fprintf(w, "\t{0x%016x, %q, %q},\n", n.key, n.eco, n.nam)
	}
	fmt.Fprintln(w, "}")
	if err := w.Flush(); err != nil {
		fmt.Fprintln(os.Stderr, "compile-openings:", err)
		os.Exit(1)
	}
	fmt.Printf("compile-openings: %d rows → %d named positions (%d unreplayable) → %s\n",
		len(rows), len(sorted), skipped, *out)
}

// openingRow is one TSV line: ECO code, full name, and the SAN move tokens.
type openingRow struct {
	eco, nam string
	sans     []string
}

// readOpeningRows reads every *.tsv in dir, keeping eco + name + the SAN tokens
// (compile-book's readOpeningLines drops eco/name; here we need them).
func readOpeningRows(dir string) ([]openingRow, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.tsv"))
	if err != nil {
		return nil, err
	}
	if len(matches) == 0 {
		return nil, fmt.Errorf("no .tsv files in %s", dir)
	}
	var rows []openingRow
	for _, path := range matches {
		raw, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		for i, row := range strings.Split(string(raw), "\n") {
			if i == 0 || row == "" { // header / blank
				continue
			}
			cols := strings.Split(row, "\t")
			if len(cols) < 3 {
				continue
			}
			rows = append(rows, openingRow{eco: cols[0], nam: cols[1], sans: sanTokens(cols[2])})
		}
	}
	return rows, nil
}
