#pragma once
// Opening NAME / ECO classifier — ported from gomachine's internal/openings
// (itself generated by `gomachine compile-openings` from the Lichess
// chess-openings dataset, CC0: github.com/lichess-org/chess-openings).
//
// Keyed by gomachine's NATIVE Zobrist key (Book::book_key() in book.cpp,
// NOT zugzwang's own Zobrist in src/zobrist.{h,cpp}) — the table was
// generated by replaying each named line through gomachine's movegen and
// hashing the final position with gomachine's pos.Key(), so runtime lookups
// here must use the SAME key scheme to match. This module is fully
// self-contained: it does not touch zugzwang's own Zobrist or TT.
//
// The Lichess matching rule ("deepest named position along the line wins")
// is what Classify() implements: given the ordered position keys of a game
// (root -> current, inclusive), the LAST key that hits the table wins, so a
// longer specific variation supersedes its parent family and a position past
// the last named node still reports the opening it came from.
#include <cstdint>
#include <string>
#include <vector>

namespace Openings {

struct Opening {
    std::string eco;
    std::string name;
};

// Parses a GMOP file at `path` (see openings.cpp for the format). Returns
// true and stores the table on success. A missing file, bad magic, unknown
// format version, or CRC mismatch is NOT fatal — returns false quietly (a
// corrupt file logs to stderr) and the classifier just always misses.
bool load(const std::string& path);
bool loaded();

// Exact-key lookup. ok=false on miss.
bool lookup(uint64_t key, Opening& out);

// Names a line given its position keys in order (root -> leaf, inclusive).
// Returns the DEEPEST (last) matching entry; ok=false if no position along
// the line is named.
bool classify(const std::vector<uint64_t>& keys, Opening& out);

} // namespace Openings
