#!/usr/bin/env node
// wasm_verify.mjs — Node harness for the zugzwang WASM build (Makefile.wasm).
//
// Loads the compiled module, hands it net.web.nnue (the pre-quantized net,
// generated by `make netweb && ./tools/netweb_writer net.nnue net.web.nnue`),
// evaluates the 24 golden FENs in test/golden_eval_web.txt and asserts EXACT
// equality against the native-computed values (integer evals — any mismatch
// means the wasm build diverges from native and must be investigated, not
// tolerated), smoke-tests `go depth N` from the start position, confirms the
// illegal-FEN gate (missing-king FEN that segfaults an ungated UCI path)
// rejects cleanly without aborting the module, and reports wasm-vs-native NPS
// at a matched depth.
//
// Usage:
//   node test/wasm_verify.mjs [--variant=simd128|relaxed] [--depth=N]
//
// Requires: the wasm build (`make -f Makefile.wasm`), net.web.nnue in the
// repo root, and (for the NPS comparison) a native ./zugzwang build.
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const args = Object.fromEntries(process.argv.slice(2).map(a => {
  const m = a.match(/^--([^=]+)=(.*)$/);
  return m ? [m[1], m[2]] : [a.replace(/^--/, ''), true];
}));
const variant = args.variant === 'relaxed' ? 'relaxed' : 'simd128';
const depth = parseInt(args.depth || '14', 10);

const jsName = variant === 'relaxed' ? 'zugzwang-relaxed.js' : 'zugzwang.js';
const wasmName = variant === 'relaxed' ? 'zugzwang-relaxed.wasm' : 'zugzwang.wasm';
const jsPath = path.join(ROOT, jsName);
const wasmPath = path.join(ROOT, wasmName);

if (!fs.existsSync(jsPath) || !fs.existsSync(wasmPath)) {
  console.error(`Missing build output: ${jsPath} / ${wasmPath}`);
  console.error(`Build first: make -f Makefile.wasm ${variant}`);
  process.exit(2);
}

// Emscripten's -sEXPORT_ES6=1 glue is syntactically ESM ("export default
// ..."), but ships as a plain .js file. Node treats .js as CommonJS unless a
// package.json declares "type":"module", and this repo intentionally has
// none — so copy the glue + wasm into a scratch dir with a .mjs extension
// (same basename, so the glue's own import.meta.url-relative wasm lookup
// still resolves) rather than mutate the real build artifact or add a
// package.json nobody asked for.
const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'zugwasm-'));
const mjsPath = path.join(scratch, path.basename(jsName, '.js') + '.mjs');
const wasmCopyPath = path.join(scratch, path.basename(wasmName));
fs.copyFileSync(jsPath, mjsPath);
fs.copyFileSync(wasmPath, wasmCopyPath);

const { default: ZugzwangFactory } = await import('file://' + mjsPath);

let lines = [];
const wasmBinary = fs.readFileSync(wasmCopyPath);

const Module = await ZugzwangFactory({
  print: (line) => { lines.push(line); },
  printErr: () => { /* NNUE/Book/Syzygy std::cerr status lines — ignore */ },
  // Bypass Emscripten's own fetch()/fs loading of the .wasm (the build is
  // ENVIRONMENT=web,worker, which assumes a browser fetch()) and hand it the
  // bytes directly — the documented mechanism for a custom host environment.
  instantiateWasm(imports, successCallback) {
    WebAssembly.instantiate(wasmBinary, imports)
      .then(({ instance, module }) => successCallback(instance, module))
      .catch(e => { console.error('instantiateWasm failed:', e); process.exit(1); });
    return {}; // signals async instantiation
  },
});

function send(cmd) {
  lines = [];
  Module.ccall('zug_command', null, ['string'], [cmd]);
  return lines.slice();
}

function loadNet(buf) {
  const ptr = Module._malloc(buf.length);
  Module.HEAPU8.set(buf, ptr);
  const ok = Module.ccall('zug_load_net', 'number', ['number', 'number'], [ptr, buf.length]);
  Module._free(ptr);
  return ok === 1;
}

console.log(`=== zugzwang WASM verification (${variant}) ===`);
Module.ccall('zug_init', null, [], []);

const netPath = path.join(ROOT, 'net.web.nnue');
if (!fs.existsSync(netPath)) {
  console.error(`Missing ${netPath}.`);
  console.error('Generate with: make netweb && ./tools/netweb_writer net.nnue net.web.nnue');
  process.exit(2);
}
const netBuf = fs.readFileSync(netPath);
console.log(`net.web.nnue: ${netBuf.length} bytes`);
if (!loadNet(netBuf)) {
  console.error('zug_load_net FAILED — refusing to continue');
  process.exit(1);
}
console.log('zug_load_net: OK');

// ---- 1. golden eval vectors: EXACT integer equality, no tolerance ----
const goldenPath = path.join(ROOT, 'test', 'golden_eval_web.txt');
const golden = fs.readFileSync(goldenPath, 'utf8')
  .split('\n')
  .filter(l => l.includes('|') && !l.trim().startsWith('#'))
  .map(l => {
    const [fen, want] = l.split('|');
    return { fen: fen.trim(), want: parseInt(want.trim(), 10) };
  });

console.log(`\n=== golden eval vectors (${golden.length} FENs) ===`);
let pass = 0, fail = 0;
for (const { fen, want } of golden) {
  send(`position fen ${fen}`);
  const out = send('eval');
  const evalLine = out.find(l => l.startsWith('eval '));
  const got = evalLine ? parseInt(evalLine.split(/\s+/)[1], 10) : NaN;
  const ok = got === want;
  if (ok) pass++; else fail++;
  console.log(`${ok ? 'PASS' : 'MISMATCH'} fen=${fen} got=${got} want=${want}`);
}
console.log(`=== golden: ${pass}/${golden.length} pass, ${fail} fail ===`);

// ---- 2. go depth 8 from startpos: legal bestmove + plausible info lines ----
console.log('\n=== go depth 8 smoke test ===');
send('position startpos');
const goOut = send('go depth 8');
const bestLine = goOut.find(l => l.startsWith('bestmove '));
const infoLines = goOut.filter(l => l.startsWith('info depth'));
console.log(`info lines: ${infoLines.length}, last: ${infoLines[infoLines.length - 1] || '(none)'}`);
console.log(bestLine || 'NO BESTMOVE');
const bestOk = !!bestLine && /^bestmove [a-h][1-8][a-h][1-8][qrbn]?(\s|$)/.test(bestLine);

// ---- 3. illegal FEN gate (missing black king — the documented segfault repro):
//         rejected without aborting the module, module still answers after ----
console.log('\n=== illegal FEN gate ===');
const badFen = '8/5ppp/8/8/8/8/5PPP/6K1 w - - 0 50';
const rejectOut = send(`position fen ${badFen}`);
console.log('reject output:', rejectOut);
const rejected = rejectOut.some(l => l.toLowerCase().includes('invalid fen'));

send('position startpos');
const stillAliveOut = send('eval');
const stillAlive = stillAliveOut.some(l => l.startsWith('eval '));
console.log('module still responsive after bad FEN:', stillAlive, stillAliveOut);

// ---- 4. NPS: wasm vs native at the same depth, real numbers not estimates ----
// ucinewgame clears the TT/history tables first — the depth-8 smoke test above
// already searched startpos and left the TT warm, which would make this run
// hit cached entries and produce a smaller, non-comparable tree. The native
// comparison process below starts fresh with no equivalent warm-up, so both
// sides need the same cold-TT starting condition for the NPS numbers (and
// node counts) to mean anything.
console.log(`\n=== NPS comparison at depth ${depth} ===`);
send('ucinewgame');
send('position startpos');
const npsOut = send(`go depth ${depth}`);
const lastInfoWasm = npsOut.filter(l => l.startsWith('info depth')).pop();
console.log('wasm:  ', lastInfoWasm);
function parseNps(infoLine) {
  if (!infoLine) return null;
  const m = infoLine.match(/nodes (\d+).*?time (\d+)/);
  if (!m) return null;
  const nodes = parseInt(m[1], 10), timeMs = Math.max(1, parseInt(m[2], 10));
  return { nodes, timeMs, nps: Math.round(nodes / (timeMs / 1000)) };
}
const wasmStats = parseNps(lastInfoWasm);

const nativeBin = path.join(ROOT, 'zugzwang');
let nativeStats = null, lastInfoNative = null;
if (fs.existsSync(nativeBin)) {
  const out = execFileSync(nativeBin, [], {
    cwd: ROOT, // native binary loads net.nnue/book.bin/syzygy cwd-relative
    // OwnBook off: native auto-loads book.bin and an opening-book hit prints
    // an instant "info depth N score ... pv ..." line with NO nodes/time
    // fields (try_book_move in uci.cpp) instead of running a real search —
    // the wasm side never has a book loaded at all, so this keeps the
    // comparison apples-to-apples (both sides doing a real depth-N search).
    input: `setoption name OwnBook value false\nposition startpos\ngo depth ${depth}\nquit\n`,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  });
  const infoLinesNative = out.split('\n').filter(l => l.startsWith('info depth'));
  lastInfoNative = infoLinesNative[infoLinesNative.length - 1];
  console.log('native:', lastInfoNative);
  nativeStats = parseNps(lastInfoNative);
} else {
  console.log('native ./zugzwang not found — skipping native comparison');
}

console.log(`\nwasm:   nodes=${wasmStats?.nodes ?? 'n/a'} time=${wasmStats?.timeMs ?? 'n/a'}ms nps=${wasmStats?.nps ?? 'n/a'}`);
console.log(`native: nodes=${nativeStats?.nodes ?? 'n/a'} time=${nativeStats?.timeMs ?? 'n/a'}ms nps=${nativeStats?.nps ?? 'n/a'}`);
if (wasmStats && nativeStats) {
  console.log(`wasm/native NPS ratio: ${(wasmStats.nps / nativeStats.nps * 100).toFixed(1)}%`);
}

// ---- summary ----
console.log('\n=== SUMMARY ===');
console.log(`golden vectors:  ${pass}/${golden.length} exact match ${fail === 0 ? '(PASS)' : '(FAIL — see MISMATCH lines above)'}`);
console.log(`go depth 8:      ${bestOk ? 'PASS (legal bestmove)' : 'FAIL'}`);
console.log(`illegal FEN:     ${rejected ? 'PASS (rejected cleanly)' : 'FAIL'}`);
console.log(`post-reject:     ${stillAlive ? 'PASS (module still responsive)' : 'FAIL'}`);

fs.rmSync(scratch, { recursive: true, force: true });

const overallPass = fail === 0 && bestOk && rejected && stillAlive;
process.exit(overallPass ? 0 : 1);
